import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { cn } from '@nextui-org/react';
import Header from './_components/Header';
import { Nunito } from 'next/font/google';
import Footer from './_components/Footer';
import { Toaster } from 'sonner'

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'FAJ - Obserwatorium',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="light">
            <body className={cn(nunito.className, "w-full")}>
                <Providers>
                    <main>
                        <Header />
                        {children}
                        <Footer />
                    </main>
                </Providers>
                <Toaster />
            </body>
        </html>
    );
}
